services:
  - type: web
    name: stirling-pdf
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile.fat
    envVars:
      - key: PORT
        value: 8080
      - key: DISABLE_ADDITIONAL_FEATURES
        value: "false"
      - key: LANGS
        value: en_GB